-- Table: Departments
CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(100) NOT NULL
);

-- Table: Teachers
CREATE TABLE teachers (
    teacher_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    department_id NUMBER NOT NULL,
    hire_date DATE NOT NULL,
    salary NUMBER(8, 2) NOT NULL,
    CONSTRAINT fk_department
        FOREIGN KEY (department_id) 
        REFERENCES departments (department_id)
);

-- Table: Students
CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    birth_date DATE NOT NULL,
    gender VARCHAR2(10),
    email VARCHAR2(100) UNIQUE,
    department_id NUMBER NOT NULL,
    enrollment_date DATE NOT NULL,
    CONSTRAINT fk_student_department
        FOREIGN KEY (department_id) 
        REFERENCES departments (department_id)
);

-- Table: Courses
CREATE TABLE courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR2(100) NOT NULL,
    course_code VARCHAR2(20) UNIQUE NOT NULL,
    department_id NUMBER NOT NULL,
    credits NUMBER(3, 1) NOT NULL,
    CONSTRAINT fk_course_department
        FOREIGN KEY (department_id) 
        REFERENCES departments (department_id)
);

-- Table: Enrollments (Many-to-Many relationship between Students and Courses)
CREATE TABLE enrollments (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    enrollment_date DATE NOT NULL,
    grade VARCHAR2(2),
    CONSTRAINT fk_enrollment_student
        FOREIGN KEY (student_id) 
        REFERENCES students (student_id),
    CONSTRAINT fk_enrollment_course
        FOREIGN KEY (course_id) 
        REFERENCES courses (course_id)
);

-- Table: Assignments (Teachers assigned to teach Courses)
CREATE TABLE assignments (
    assignment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    teacher_id NUMBER NOT NULL,
    course_id NUMBER NOT NULL,
    assignment_date DATE NOT NULL,
    CONSTRAINT fk_assignment_teacher
        FOREIGN KEY (teacher_id) 
        REFERENCES teachers (teacher_id),
    CONSTRAINT fk_assignment_course
        FOREIGN KEY (course_id) 
        REFERENCES courses (course_id)
);

-- Table: Classes (Course schedules)
CREATE TABLE classes (
    class_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id NUMBER NOT NULL,
    class_date DATE NOT NULL,
    room_number VARCHAR2(20) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_class_course
        FOREIGN KEY (course_id) 
        REFERENCES courses (course_id)
);
